### ISSUE TITLE
Missing the "Not a Hotdog" theme

### ISSUE THREAD

**Issue by TheCodeArtist** [pmn/randos.online#5]
Hello,

you are a missing theme - "Not a Hotdog".

![image](https://user-images.githubusercontent.com/1897177/87335219-91627280-c55d-11ea-809c-bf0d420ab57e.png)

your friend
Jin Yang

PS: Erich is a Lying person.

**Reference**: https://www.youtube.com/watch?v=vIci3C4JkL0

**Comment by pmn** [comment]
@TheCodeArtist :joy: you got it! `theme=nothotdog` will do it for you (note, there's no *a* in the theme name)
